services:
  angie:
    image: docker.angie.software/angie:latest
    container_name: angie
    network_mode: host
    ulimits:
      nofile:
        soft: 16384
        hard: 16384 
    volumes:
      - ./angie.conf:/etc/angie/angie.conf
      - ./options-ssl-angie.conf:/etc/angie/options-ssl-angie.conf
      - ./acme/:/var/lib/angie/acme/
      - ./.htpasswd:/etc/angie/.htpasswd
      - /opt/angie/logs/:/var/log/angie/
    restart: unless-stopped

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    network_mode: host
    volumes:
      - ./db/:/etc/x-ui/
      - /opt/x-ui/logs/:/var/log/x-ui/access.log
      - /opt/x-ui/logs/:/var/log/x-ui/error.log
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "false"
    tty: true
    restart: unless-stopped

  authorization-stub:
    image: ampetelin/authorization-stub:latest
    container_name: authorization-stub
    network_mode: host
    restart: unless-stopped
